[[Octave]]
arch = "aarch64"
git-tree-sha1 = "62da7decd4d23a2b360bc02a872db5ebee5fc9b1"
os = "macos"

    [[Octave.download]]
    sha256 = "d7dfe37e17922a33d7908af1c111c9e0e3bb6ad9fd34a96556fecdb235ff9662"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.aarch64-apple-darwin.tar.gz"
[[Octave]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "210489bcea6bd23fc5fc844d4589f3a5e8ffd4d1"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "35835bdbd4756c98703b3c2de5e4a21bf5a4f17a92eea35ed90500f6851f7bc4"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Octave]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43609b5191818a80f72e81c4aabb063fdf3c395e"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "c309a56b1fd154d6d0618e120a71f40811a4d9cd159076795109811b59bccd08"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Octave]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0216c9df09eb07d6fddab061d47f8d6b3d3e5736"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "181ede1aa1c19db6bdd57607d2b87efdb93df985e4883cc0147827d50feed004"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[Octave]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "da1444a35f7a1d95af8e8c0d3af220230e1884df"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "8a69ac2d4b40beaf9f3e0dab68db86fec4778a01eb6d582868ebbe4b734446c6"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[Octave]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80062b464ab58a6a491dcf616b33ad09a2a7c299"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "782d0bcc1fb5f3cbd7c35feaff55c5b0f05f6b8ce5b1be3eeea3690d0c9a502d"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Octave]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68266d97ec81c3cb6419f885087f7c3b944059f7"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "9dbecbbdd856fecac065def91cf0f8d95dd0f712901a38c80e986b3ae61d2e2d"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Octave]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8ed202fb120570ad1693f4dda149fadcde9eecc4"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "04543a02308269b5a519d28f622fbf4db4ae50f9411ebc1be3e5fa851080d0fd"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Octave]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47a8246d20b1d41cf066d2bbb5e0649162d78384"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "db25ca1f1a0e37933142d2c33bd9cc78608cf1e0b8e9337f1a585717b8e25ed4"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Octave]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc1fffa2da1b2597fcf66c0e0dee1567604eade3"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "921aec3e0126ba39e9bfa38a5afc8d5fc9520b0e30490302c084ea99353098ce"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Octave]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c8359a3a32331506114ff8abf51113770177dc69"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "2f7081a73b1c0ceed49e8692a412259fb7f99eb7fa70d435cf2adb4adf96b7e0"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Octave]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "94198024994625a73e1cfb1bf8f7d7bb645e80bd"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "14a03f2573bd4d1fd8aeeda947a2892fcc8b858998e62cf3140f73d5bd67ecc8"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Octave]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "07fed268ed7eacff23e85691a477095986a92d33"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "37e89420d9738d03d44abaa915dd157e3eebd01356c3b5ea2bf4aff55195ce45"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Octave]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f1e6d0abd1d3c079a9a42a6941db859316b61965"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "046af7009c37b6ef1fa47ac2e8773c43456b89f9acce000e62754d479ce58c25"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.i686-linux-gnu-cxx03.tar.gz"
[[Octave]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bdde664e588d84786c8c42efd26a956b6aeeb11d"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "881ceddbbc52b1952273190da10034c4ad4ad63620d0704dae65358cdbc5229c"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.i686-linux-gnu-cxx11.tar.gz"
[[Octave]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f7afc1ea54b92c537744d922f32af3afea88a3c3"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "45ec011ad0a5478b525d367012df6f1425ef97deb3413115ba49f518f4aec2c6"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.i686-linux-musl-cxx03.tar.gz"
[[Octave]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b93d30543c4906c68bb3c46bb80558c99158ab00"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "b0e91487fd54c558f24809814afd30b9521ebc9a76049812987e1d56db1de383"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.i686-linux-musl-cxx11.tar.gz"
[[Octave]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4a5d5be9ab2d1301ed63eff922298f19ce2e890f"
os = "windows"

    [[Octave.download]]
    sha256 = "e5969146582a02918832ef2276627b0d0a7705f28d00d7925200a964abc85af2"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.i686-w64-mingw32-cxx03.tar.gz"
[[Octave]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43436457b1643a49919e88d00448a736137b27f5"
os = "windows"

    [[Octave.download]]
    sha256 = "52716eb4f7e8d4dce90f7c349f441bc189a167a4efffb27bf5195b58a97a8e47"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[Octave]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "74d404335759aab68a71f3762438792b99339aa6"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "fcee2c42dde3127a5a5c96b725ca19bfae77e003cecb22abf070e09f15c71852"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Octave]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a7270e87d238ca159d17984a7ce7614371756e8"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "f7b3ba118900d10fc8c774a9e91fe51a6fc80925c27f84da4b35029f2e06a186"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Octave]]
arch = "x86_64"
git-tree-sha1 = "fb43cc7651415c2ef9d61b583776975048a9dc8b"
os = "macos"

    [[Octave.download]]
    sha256 = "2188dd951fd2b59eab6472a40e5f343bedbd61564c3d032e0d060e708a124350"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.x86_64-apple-darwin.tar.gz"
[[Octave]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9bb46a09360831fb44f70679e9ab2829dc734e80"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "c6da404ce301d4cad961b918ecd7cdb09aef8b20f582befb31defe87d9693e8f"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Octave]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d117067884de6e9a70dd5575aba6ddaccefdf711"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "734d0211b8d5961248bbec962e429f89ce3aadb21079b7636099a89e59046f8b"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Octave]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "61615a9c0128c124d45ea3f6e21c15d409dfee4d"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "e03bc61a42c77cafb2fdf5d86314d6bb62e0464e6a54546713967b12b36e9bc4"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[Octave]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5547cebdc699b9e7e4795a6a527eab1f17dc29ab"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "2e0c060a1731b18f65eca2bb843e7c6491ca2a4f2e7e309cf6db032ab99b480d"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[Octave]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "33f1ddcd95c6f1f9fb44a58de525eb98ce60d0ed"
os = "windows"

    [[Octave.download]]
    sha256 = "01fbf40fc76701d23e73c0b6a54e7b4e1ac971e7e4c4a42e635c98bc1d8c03ea"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Octave]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93d1a759ee90cdbec72da08c2cf98ec376224a2b"
os = "windows"

    [[Octave.download]]
    sha256 = "f4a00a412f777dc1c8f55b9fa411b51e691df7754a155c0a3816bb15188f8e0a"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+1/Octave.v9.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
