[[Octave]]
arch = "aarch64"
git-tree-sha1 = "9e380d40f287e23ab612da94083cb527be5c6a4c"
os = "macos"

    [[Octave.download]]
    sha256 = "3857e202f882953c01759380a1fdd0c25bc0e9855b806de598381a0b35e1e3b8"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.aarch64-apple-darwin.tar.gz"
[[Octave]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "48f845b110f2edbf97b28c8f8fd07fd7a1a58ae8"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "ceef8f8c8cec8cf967af0f8b1363455219c363054264276784da790042508436"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Octave]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a632df1a48169ecb739433d1f648b9221dd1087e"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "e551bdc560931c7099501b5eea843cb8118ca0ecabd08d2183ce2a3693330e09"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Octave]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "beedb9d033a96bc9a437f983965c9d72024d6cdb"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "b81d8ac8c26009a22bb7e4adfa5b168c3f3c9bd7e2767cbf2cb884d17c105381"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.aarch64-linux-musl-cxx03.tar.gz"
[[Octave]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a0e0729c2c36312bd072a9e9c8157e7dc2cead2"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "a6e469ee3bb3a496cc86251e67ea6777d29d1f1be93d1e304769186068dffdbd"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.aarch64-linux-musl-cxx11.tar.gz"
[[Octave]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a9cc05b66ba07eeb19f6f4380f0380ba17b9a6f0"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "b78a39c9a855370303a065ae0bb523784da4b7c3b43a0b1f88cd5be3b813ea1b"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Octave]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dd30d779c623b670aa91ea63c49097c5e1755054"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "1552244ea933f4146d17c20942359bccf843b50a291cb8592e6241a05a208b39"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Octave]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ca94e6cd82dca7b33e12f0d7b52a6517a218c174"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "b54c1a29384d12044840e0587019eedb4a30703e0755fabb7862922d8dfcda25"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Octave]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4dc5868e709148036bd4d85568f48c5e976e0073"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "1c57185c212745071aee1e5f75807311fc83387713453afe17c09108dd0ef7d6"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Octave]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6bcdae4900d12fb44141b12417fd78e19f31dbb2"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "d0180091169b5ef73d7e270440ee3c9b1e05a8ec21a71b8923d293a6f7c13db2"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Octave]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dafeca391428935c15d5fa0014684993162d3da3"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "b8a2150f4c62852275c8859db031d29f97dcadee9624ad4d47f82aadac5c02f2"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Octave]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0cb1f65e25991662f837dd09a0cc5a5aee230f86"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "28e2db4ac22f8b10c5d641b72aa5afcf03fc9d51a1265bb4e53dfe4bf798b7c9"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Octave]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10b911cf0ea259d984bda973b92abff6d9c7b50a"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "0dac31f1569837319f009117fc9caa293b196b411e08f270ff4a23e89fa942f2"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Octave]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae07484c4c3ba28e11679a0c22fdbdfef3e97f3f"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "25efd4c1dcddfefb103bde04924f6d7a3e1ce14a6fb26cc378a39a865ff75844"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.i686-linux-gnu-cxx03.tar.gz"
[[Octave]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a8f2dda81784cb3954e16609582ad81ccb62e61b"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "6a7e2a5b6c9938f35de2e9067d4db8f066f6bdbaf218ba0da916aa5777410607"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.i686-linux-gnu-cxx11.tar.gz"
[[Octave]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bc9a74bcfc2d73ecfe954f6709463a614aef4f9f"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "5ce9afd219f02855d1f104135e33ac2598f58844ef0eb6f4e1f5d56b35cd94e7"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.i686-linux-musl-cxx03.tar.gz"
[[Octave]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68b793beb8ab569bcaa4cd65b118bb4217864821"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "2251d1e8760bbdc45511797897b318d260408040e0becf3a796b7267136bc503"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.i686-linux-musl-cxx11.tar.gz"
[[Octave]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05afbb9bc8d57a5fc79e4e4a48dfd9a393005137"
os = "windows"

    [[Octave.download]]
    sha256 = "ddacbd36f84cdece09de851ada134e83c003f41669929fe4a235d5e07bbc9c76"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.i686-w64-mingw32-cxx03.tar.gz"
[[Octave]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dfce612fb4c26d78f9824f33448092078a94a926"
os = "windows"

    [[Octave.download]]
    sha256 = "02088e392d478bd195e95ffda21947bc7dfb3d11110e95ec3658c9a11512bbfb"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.i686-w64-mingw32-cxx11.tar.gz"
[[Octave]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72f91e82102cd53c26cb32367785b5830458c0df"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "d3b66722b5e3d6072cbacc36123a3cf7799420eda479af299818f0b5d7ebe572"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Octave]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dfe0d665e94a96efc3d2c3b46d61705f8e0e3e07"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "0ea078dffdefbcc5c153dbae0cd4dfdbba6a17e2f5ac15d020fc3ba6f67a0f81"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Octave]]
arch = "x86_64"
git-tree-sha1 = "01a9237de5fa10ffa3038dc6cf5847b50354b584"
os = "macos"

    [[Octave.download]]
    sha256 = "47084cd2fd95da4dc01a2041861516a1f7c776dd5db68a2094415452599f8c74"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.x86_64-apple-darwin.tar.gz"
[[Octave]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "37bf180c845c11c88fbe5606b2d99e8918877721"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "8cf8d1d543d9caa8d077b261c28c76edb15400e31fb05f2eea07efa3c139011e"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Octave]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5419972a5ef56b7d82d504ffae431c5423014ec5"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "3cef2c2bdc9504dcb7ea40280a989505668a161a388228c3e044f13cce5795f5"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Octave]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e64822d480eed58c7bdbcf0ccc021070e9fb543"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "6d1dec7188f53b40c95c7f6c70f07266c6af657229cf6dbd6374ae5e1b382ae3"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.x86_64-linux-musl-cxx03.tar.gz"
[[Octave]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2be18801d3db60e71ba17547a597eca5d17a839c"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "9a4af9b1b328c33ef6cbc42622e45d93a30db52717f8b2f66fa46240854fc72e"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.x86_64-linux-musl-cxx11.tar.gz"
[[Octave]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a29b398fee949827627a3ff087b027dd978b54d"
os = "windows"

    [[Octave.download]]
    sha256 = "13d9d5ec269335485f43aa552166f1f14993f577949adc1a569255a93bd0a77c"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Octave]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "15094ae06059d842ce8ab08505a05f37756f9bcd"
os = "windows"

    [[Octave.download]]
    sha256 = "b916672c8dbbc42ab565cc104b1701013074078790ee3d75900040de90a14ece"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.2.0+0/Octave.v9.2.0.x86_64-w64-mingw32-cxx11.tar.gz"
