[[Octave]]
arch = "aarch64"
git-tree-sha1 = "f408943f78db73b219d07420940859befd2877b1"
os = "macos"

    [[Octave.download]]
    sha256 = "0ae3d8104f469e48e401735f22a3cab5253a94e402a57f7c9ed469c33a3f3633"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.aarch64-apple-darwin.tar.gz"
[[Octave]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b0b02edb3b0752c3ff62f60d43e7b35dd53bf201"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "21f604f7630f7fa4116f5120601ba9557857c6a421a2d1f53a4ecd2fa02c31eb"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Octave]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea68111c3eab8e31277c6eab662c84cfb4eecfad"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "ad2d31b5f9316f620fde9c0c34851cfb0716826ccbc607c6d7e61c2be1fec98b"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Octave]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05b466c4e76bbdc19c034d156d10af8a4630e7f5"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "8825f62c83ccfaa032a3f1159f755159f93891013b575447ccac10eecc2dc766"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.aarch64-linux-musl-cxx03.tar.gz"
[[Octave]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e12733dc07c2eeba1ecf6f3127b4866d8debb27"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "c16eaeb14c7becdbd33b8b57b518ec1929ba04a6e354170a75b86e18f03b7f78"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.aarch64-linux-musl-cxx11.tar.gz"
[[Octave]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5abe1ddb34176f3253a22fee7a23921de2157bed"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "1506a4170a2c7e2970ad30afea791c72de58089dcc904d14841f83578c23c5ea"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Octave]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c193952bea82d8d0d0f92a1568ec8b9e2fb25203"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "ac41c63ea8825cf28bd5233f0ddacc904d193be74f8b1b4c305fb10d0088c8a2"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Octave]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fe251d0709ac4ded3332679a812f7f5d19c2c0fc"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "1e17aa6a094431530c8fb607cb5e19f981cde9181ae9ed39de2b72dc8fa954cc"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Octave]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "020f30f95f47606625e520efdd55dd0b3542ab9f"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "f781f32824fae331ce4cecfadd58e45ed31e55cb8e85481abdecac5a70537727"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Octave]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9a6b0375c49246412be75ab8577074428a41f9ab"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "4a48bf8476633e2dc83ac0b6593892980ddc437c9455ed5a7e76792bb55c9fc5"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Octave]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe85358e53de478e2aa35976785a4bed9b247bc6"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "28a8d7a03f971688a1819131ce3e88d93665026eb1b50a9f3ca9eec64e43d2e1"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Octave]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "207814aa84bb05824c8e4d43dc619e308aa5abc0"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "71023b0e96e25f3a9fc259ba5de78540f79829b2a99376f1b4083f0c34777f3d"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Octave]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81303a9ac4b9e96bac24407a3961b06da689a3c2"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "80f4e511582a080d9565296901dacf58fbbd9b353d83ad7cec50699fd4adbf14"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Octave]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9633406d09c38a1b365d1edd0741312709995e01"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "1e72146ca369b2d77049e3cce7184d051593f99561f72ad1706c6fbbe866fc27"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.i686-linux-gnu-cxx03.tar.gz"
[[Octave]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e2c4027d4fb75d1d81be155f9ca444de9fd5e4ab"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "5f09c90dfbb3dfaa89b5a6e3e117baa03f84098ad7cc960293f5c99467e4f7bb"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.i686-linux-gnu-cxx11.tar.gz"
[[Octave]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "30e252f6679e7e3c6c0442e2117aa71d59f37d5f"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "c30a77d63a2b88fc173b744fc2384f873bd33aca8da1031cddb07551cd7ff0ea"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.i686-linux-musl-cxx03.tar.gz"
[[Octave]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94a2ac6a6e9746aa8b373a7c1a1f54d8ba5047d5"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "a9be9ec3b0c340936652b1c294d09cc7550574ca1d21daee50426b60756a2e93"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.i686-linux-musl-cxx11.tar.gz"
[[Octave]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "526ca7219ba722c316e777c4b8e28471abdc77dd"
os = "windows"

    [[Octave.download]]
    sha256 = "097d7eb268a5fe758e9f76b5204521af0cf5aae92bd5c3ce7eae75f3a8aa2a76"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.i686-w64-mingw32-cxx03.tar.gz"
[[Octave]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b42346e88cd444a68aacad45a4749377bd5bdea7"
os = "windows"

    [[Octave.download]]
    sha256 = "7f55be26c24a3b0d95f36dc9691315eebd03f724e5449282e71e2b7e534099c0"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.i686-w64-mingw32-cxx11.tar.gz"
[[Octave]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a898c5a0cd60024d1e35aa7be9d7291074661281"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "851b47afc1d799ce658054e42339e458f30cd9f6509152160690bb24088b430c"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Octave]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e1bf24dbbc001967391132a2d8325b85939075f"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "35e6f3926e6107b2bafbd80d711a9d1360d79d50100c9ce2dc623504e5188de4"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Octave]]
arch = "x86_64"
git-tree-sha1 = "80647c4c6aa46bb5a7a25a2708f4c625e66aba5f"
os = "macos"

    [[Octave.download]]
    sha256 = "68bd85cf63224f1fa71111aad0b5b537e7551de80fec33fab1c1a2a2eff95f2a"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.x86_64-apple-darwin.tar.gz"
[[Octave]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "02a8f3ed8ac4e85c98ec7e1eea3b4056728b15fa"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "39e9c687060bc60556c3639788c07dbe2039c4834ba4b8efe914d8396e939763"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Octave]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56eb0a44bd2e07c6e5829bd94f40a3327bec94fc"
libc = "glibc"
os = "linux"

    [[Octave.download]]
    sha256 = "f2707bcda759422bedaae56f44dad174d903dc1e7ae55cd3e1e682e4ddb740ac"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Octave]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9f57a06c953c28a1704a0241066482e046adb020"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "10789288a1f1027599eda42843a3515596ee734bfe3d4ca7469e4d9e98fb22a9"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.x86_64-linux-musl-cxx03.tar.gz"
[[Octave]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7bd9f5436f38a0eff3a46c6b37ca81143ec4e619"
libc = "musl"
os = "linux"

    [[Octave.download]]
    sha256 = "a7b3c97b25ec90a9ba7e3ecfa88fe65613258792258a1d076bebe26b43788f6e"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.x86_64-linux-musl-cxx11.tar.gz"
[[Octave]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9835330200cd698c031f0eed67b485881d2ec84f"
os = "windows"

    [[Octave.download]]
    sha256 = "47427b9ec02f57ee165d28a3e493b84d09088022526b321b1e68095209085fbc"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Octave]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ae9594d9a15852658fbf9f5362de8d0c35cedc8"
os = "windows"

    [[Octave.download]]
    sha256 = "fa699ae79bcee045f4177a233e0ebdecaab0143ec1206d2779251bfbe2476d61"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v9.3.1+0/Octave.v9.3.1.x86_64-w64-mingw32-cxx11.tar.gz"
