[[Octave]]
arch = "aarch64"
git-tree-sha1 = "efc0ddaee07d79459d1af2f9e2f6be6dce9a5e77"
libgfortran_version = "5.0.0"
os = "macos"

    [[Octave.download]]
    sha256 = "c0d6c41197bd8c3c12ccd75aa318f3ce2f08e52cc16395d0110c5859543d8546"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v11.1.0+0/Octave.v11.1.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Octave]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "539e9dc51551d6e8234521423b11e4723db205fa"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Octave.download]]
    sha256 = "500acfdf11160340f7668a2ad8dd7f6c774127f987e43344a1211cd5478f0b2d"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v11.1.0+0/Octave.v11.1.0.aarch64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Octave]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "28ed394e3296d1c899bbc841064329ac8cc0e34d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Octave.download]]
    sha256 = "076f561721fbbc69d59d2cd64e28d5f52f1bfcc6af68c1fb70ad64cd7219b090"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v11.1.0+0/Octave.v11.1.0.aarch64-linux-musl-libgfortran5-cxx11.tar.gz"
[[Octave]]
arch = "aarch64"
git-tree-sha1 = "5bd46280b6bf1bb6edd956a57712244d5f2086d6"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Octave.download]]
    sha256 = "07b009ca888cf453523e752fcc683e7e604f3eeb366e63be15aea6c277766147"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v11.1.0+0/Octave.v11.1.0.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[Octave]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa89eb3f49a7366b5e52c6d8df0d25f32fdc1311"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Octave.download]]
    sha256 = "2ba0e4d13e22ffb65eaa870f7d8b0ab3d4a3fd50d23a1fc3419d9473186c4ed7"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v11.1.0+0/Octave.v11.1.0.armv6l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[Octave]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "308f854d75af6554f4ef3c76de275025b9e91ce2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Octave.download]]
    sha256 = "17bf02026c290c1bdc2f131c5c1090dcf928cadf798e7c1aa75588174e61c2df"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v11.1.0+0/Octave.v11.1.0.armv6l-linux-musleabihf-libgfortran5-cxx11.tar.gz"
[[Octave]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7328b639e5d95fcc666c54848213bca501477854"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Octave.download]]
    sha256 = "759e907d90ddc803201b79740fd6bb323f999a624436c2e9d6be1dc91739ebe1"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v11.1.0+0/Octave.v11.1.0.armv7l-linux-gnueabihf-libgfortran5-cxx11.tar.gz"
[[Octave]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a2168f2764d6ba51877041a89576d43a40276e63"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Octave.download]]
    sha256 = "070bc13a54907910428566aff5c170b28b905089a0f7c5bd09c7c5e051bc7eae"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v11.1.0+0/Octave.v11.1.0.armv7l-linux-musleabihf-libgfortran5-cxx11.tar.gz"
[[Octave]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4f022467224e1b51a917814f059c82e9fc03223"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Octave.download]]
    sha256 = "0a920accccab9a0736fd9772a4f4fbbc17b15b73a8395e39b1511e76d7e4817a"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v11.1.0+0/Octave.v11.1.0.i686-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Octave]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68a5d6cb88dc930fd676591c10ab15de568f496a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Octave.download]]
    sha256 = "531c7ae263ddfab908b97714d93997c1ad7201951473b5c8591228545d5434c7"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v11.1.0+0/Octave.v11.1.0.i686-linux-musl-libgfortran5-cxx11.tar.gz"
[[Octave]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0b8f13af7b6ebcde1415babc75aa744783531f71"
libgfortran_version = "5.0.0"
os = "windows"

    [[Octave.download]]
    sha256 = "06d6bed516d56aef3ddf06ab456611628ada5fc08c423e18e8d582eb7af5e91d"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v11.1.0+0/Octave.v11.1.0.i686-w64-mingw32-libgfortran5-cxx11.tar.gz"
[[Octave]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b7d75ff27fb33b5387de94dd3e34194d17b10a7f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Octave.download]]
    sha256 = "76bbdcdc3dc5e3185529d9543a2fae03b5e984580835e909336a78e9f695ab6a"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v11.1.0+0/Octave.v11.1.0.powerpc64le-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Octave]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4396fe7bc1a0fd0511f9c9ec4412d40076e75e22"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Octave.download]]
    sha256 = "0a7655bc021904d17c0d9b2f442a4465dfa4c57177488ef2ed3d18ea64f86588"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v11.1.0+0/Octave.v11.1.0.riscv64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Octave]]
arch = "x86_64"
git-tree-sha1 = "2a107b6a3c6006b1a1c49013cbce9653e28ff912"
libgfortran_version = "5.0.0"
os = "macos"

    [[Octave.download]]
    sha256 = "128397f5b10d1eda4a1161abc486fe20bc7157179a279081063cb325f48c26f3"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v11.1.0+0/Octave.v11.1.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Octave]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c216179fe22515745c55b4af4ae8295b4a5ed73"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Octave.download]]
    sha256 = "0b09ffb64b7fdf9702b71d232bbac9c98770e171d5a141d01f0c7dac1473b543"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v11.1.0+0/Octave.v11.1.0.x86_64-linux-gnu-libgfortran5-cxx11.tar.gz"
[[Octave]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2e451830467312613119f2458f95e1546a17c42"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Octave.download]]
    sha256 = "b60b6c42d9bfe5320de52e49e552afaf88ccd92e5cdb70c1566da257191c0e64"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v11.1.0+0/Octave.v11.1.0.x86_64-linux-musl-libgfortran5-cxx11.tar.gz"
[[Octave]]
arch = "x86_64"
git-tree-sha1 = "c1b5dd86ee19a697e431131225f27916f2dddd2b"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Octave.download]]
    sha256 = "53c7c74828fbe4bffa2a8220bc4cc0aa3a62cfa3ff08c2fcb0eea97c82ce9c7f"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v11.1.0+0/Octave.v11.1.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Octave]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2413a7623fa341e5787b5ddabb2e01ffb1378267"
libgfortran_version = "5.0.0"
os = "windows"

    [[Octave.download]]
    sha256 = "230d22419dfa79c33547cef30fadf202e643ec949b0b2ca23569a1d775423ae0"
    url = "https://github.com/JuliaBinaryWrappers/Octave_jll.jl/releases/download/Octave-v11.1.0+0/Octave.v11.1.0.x86_64-w64-mingw32-libgfortran5-cxx11.tar.gz"
